imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
      handler_id:  ~
      storage_id: session.storage.filesystem
      name: MOCKSESSID

    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# doctrine:
#     dbal:
#         default_connection: default
#         connections:
#             default:
#                 driver:   pdo_sqlite
#                 path:     "%kernel.cache_dir%/test.db"
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%_test'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

liip_functional_test:
    cache_sqlite_db: true
    authentication:
        username: "admin_user"
        password: "secure_password"

